name: GlassSkyTools
options:
  bundleIdPrefix: com.sky.glasshelper
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

targets:
  GlassSkyTools:
    type: application
    platform: iOS
    sources:
      - path: GlassSkyTools
    info:
      path: GlassSkyTools/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.7"
        CFBundleVersion: "7"
        CFBundleDisplayName: 进阶助手
        LSRequiresIPhoneOS: true
        UIRequiresFullScreen: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsArbitraryLoadsInWebContent: true
        UILaunchScreen:
          UIImageName: app_bg
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sky.glasshelper
        PRODUCT_NAME: GlassSkyTools
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0.7"
        CURRENT_PROJECT_VERSION: "7"
        ENABLE_BITCODE: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: "NO"
        DEVELOPMENT_TEAM: ""
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    scheme:
      testTargets: []
